import { db } from "./index";
import { funds, positions } from "./schema";

async function seed() {
  // Clear existing data
  await db.delete(positions);
  await db.delete(funds);

  // Insert funds
  const insertedFunds = await db
    .insert(funds)
    .values([
      {
        name: "Global Trade Fund I",
        fund_type: "Equity",
        base_currency: "USD",
        aum_usd: 1240.5,
        inception_date: "2018-03-15",
        manager: "Alexandra Chen",
        status: "Active",
      },
      {
        name: "Emerging Markets Fixed Income",
        fund_type: "Fixed Income",
        base_currency: "USD",
        aum_usd: 875.2,
        inception_date: "2019-07-01",
        manager: "Marcus Okonkwo",
        status: "Active",
      },
      {
        name: "Commodities & Resources",
        fund_type: "Commodity",
        base_currency: "USD",
        aum_usd: 420.8,
        inception_date: "2020-11-10",
        manager: "Sofia Andersen",
        status: "Active",
      },
      {
        name: "Multi-Asset Compliance Fund",
        fund_type: "Multi-Asset",
        base_currency: "USD",
        aum_usd: 560.0,
        inception_date: "2021-04-20",
        manager: "James Whitfield",
        status: "Active",
      },
    ])
    .returning();

  const [gtf, emfi, cr, macf] = insertedFunds;

  // Fund 1: Global Trade Fund I (Equity)
  await db.insert(positions).values([
    {
      fund_id: gtf.id,
      security_name: "Apple Inc.",
      ticker: "AAPL",
      isin: "US0378331005",
      asset_class: "Equity",
      country: "United States",
      sector: "Technology",
      quantity: 42000,
      price_usd: 189.3,
      market_value_usd: 7950600,
      weight_pct: 8.94,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Microsoft Corporation",
      ticker: "MSFT",
      isin: "US5949181045",
      asset_class: "Equity",
      country: "United States",
      sector: "Technology",
      quantity: 28500,
      price_usd: 415.2,
      market_value_usd: 11833200,
      weight_pct: 13.31,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "ASML Holding NV",
      ticker: "ASML",
      isin: "NL0010273215",
      asset_class: "Equity",
      country: "Netherlands",
      sector: "Technology",
      quantity: 8200,
      price_usd: 720.5,
      market_value_usd: 5908100,
      weight_pct: 6.65,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Samsung Electronics",
      ticker: "005930",
      isin: "KR7005930003",
      asset_class: "Equity",
      country: "South Korea",
      sector: "Technology",
      quantity: 95000,
      price_usd: 58.4,
      market_value_usd: 5548000,
      weight_pct: 6.24,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Alibaba Group Holding",
      ticker: "BABA",
      isin: "US01609W1027",
      asset_class: "Equity",
      country: "China",
      sector: "Technology",
      quantity: 38000,
      price_usd: 74.2,
      market_value_usd: 2819600,
      weight_pct: 3.17,
      compliance_status: "Review",
    },
    {
      fund_id: gtf.id,
      security_name: "Baidu Inc.",
      ticker: "BIDU",
      isin: "US0567521085",
      asset_class: "Equity",
      country: "China",
      sector: "Technology",
      quantity: 22000,
      price_usd: 92.1,
      market_value_usd: 2026200,
      weight_pct: 2.28,
      compliance_status: "Review",
    },
    {
      fund_id: gtf.id,
      security_name: "Reliance Industries",
      ticker: "RELIANCE",
      isin: "INE002A01018",
      asset_class: "Equity",
      country: "India",
      sector: "Energy",
      quantity: 185000,
      price_usd: 28.6,
      market_value_usd: 5291000,
      weight_pct: 5.95,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Nestlé SA",
      ticker: "NESN",
      isin: "CH0038863350",
      asset_class: "Equity",
      country: "Switzerland",
      sector: "Consumer Staples",
      quantity: 62000,
      price_usd: 98.4,
      market_value_usd: 6100800,
      weight_pct: 6.86,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Shell PLC",
      ticker: "SHEL",
      isin: "GB00BP6MXD84",
      asset_class: "Equity",
      country: "United Kingdom",
      sector: "Energy",
      quantity: 145000,
      price_usd: 31.8,
      market_value_usd: 4611000,
      weight_pct: 5.19,
      compliance_status: "Clear",
    },
    {
      fund_id: gtf.id,
      security_name: "Toyota Motor Corp.",
      ticker: "7203",
      isin: "JP3633400001",
      asset_class: "Equity",
      country: "Japan",
      sector: "Consumer Discretionary",
      quantity: 78000,
      price_usd: 21.5,
      market_value_usd: 1677000,
      weight_pct: 1.89,
      compliance_status: "Clear",
    },
  ]);

  // Fund 2: Emerging Markets Fixed Income
  await db.insert(positions).values([
    {
      fund_id: emfi.id,
      security_name: "Brazil 10Y Sovereign Bond",
      ticker: "BRZGB10",
      isin: "BRSTNCNTB1Y5",
      asset_class: "Bond",
      country: "Brazil",
      sector: "Government",
      quantity: 12000000,
      price_usd: 0.92,
      market_value_usd: 11040000,
      weight_pct: 12.61,
      compliance_status: "Clear",
    },
    {
      fund_id: emfi.id,
      security_name: "India 7Y Government Bond",
      ticker: "INGB7Y",
      isin: "IN0020240070",
      asset_class: "Bond",
      country: "India",
      sector: "Government",
      quantity: 9500000,
      price_usd: 0.95,
      market_value_usd: 9025000,
      weight_pct: 10.31,
      compliance_status: "Clear",
    },
    {
      fund_id: emfi.id,
      security_name: "Mexico 5Y Sovereign Bond",
      ticker: "MXGB5Y",
      isin: "MX0MGO000016",
      asset_class: "Bond",
      country: "Mexico",
      sector: "Government",
      quantity: 8200000,
      price_usd: 0.97,
      market_value_usd: 7954000,
      weight_pct: 9.09,
      compliance_status: "Clear",
    },
    {
      fund_id: emfi.id,
      security_name: "Indonesia 10Y Bond",
      ticker: "IDGB10",
      isin: "ID1000122903",
      asset_class: "Bond",
      country: "Indonesia",
      sector: "Government",
      quantity: 7800000,
      price_usd: 0.89,
      market_value_usd: 6942000,
      weight_pct: 7.93,
      compliance_status: "Clear",
    },
    {
      fund_id: emfi.id,
      security_name: "Gazprom Capital Bond 2026",
      ticker: "GAZPRU",
      isin: "XS0424894061",
      asset_class: "Bond",
      country: "Russia",
      sector: "Energy",
      quantity: 5000000,
      price_usd: 0.18,
      market_value_usd: 900000,
      weight_pct: 1.03,
      compliance_status: "Restricted",
    },
    {
      fund_id: emfi.id,
      security_name: "Russia Federal Bond OFZ",
      ticker: "RUFZ30",
      isin: "RU000A0JXTS3",
      asset_class: "Bond",
      country: "Russia",
      sector: "Government",
      quantity: 6000000,
      price_usd: 0.12,
      market_value_usd: 720000,
      weight_pct: 0.82,
      compliance_status: "Restricted",
    },
    {
      fund_id: emfi.id,
      security_name: "South Africa 8Y Bond",
      ticker: "ZAGB8Y",
      isin: "ZAG000047718",
      asset_class: "Bond",
      country: "South Africa",
      sector: "Government",
      quantity: 7200000,
      price_usd: 0.93,
      market_value_usd: 6696000,
      weight_pct: 7.65,
      compliance_status: "Clear",
    },
    {
      fund_id: emfi.id,
      security_name: "Turkey 5Y Sovereign Bond",
      ticker: "TRGB5Y",
      isin: "TRT270125T19",
      asset_class: "Bond",
      country: "Turkey",
      sector: "Government",
      quantity: 6500000,
      price_usd: 0.82,
      market_value_usd: 5330000,
      weight_pct: 6.09,
      compliance_status: "Review",
    },
    {
      fund_id: emfi.id,
      security_name: "Colombia 6Y Bond",
      ticker: "COGB6Y",
      isin: "CO0000000EF2",
      asset_class: "Bond",
      country: "Colombia",
      sector: "Government",
      quantity: 5800000,
      price_usd: 0.91,
      market_value_usd: 5278000,
      weight_pct: 6.03,
      compliance_status: "Clear",
    },
  ]);

  // Fund 3: Commodities & Resources
  await db.insert(positions).values([
    {
      fund_id: cr.id,
      security_name: "SPDR Gold Trust ETF",
      ticker: "GLD",
      isin: "US78463V1070",
      asset_class: "ETF",
      country: "United States",
      sector: "Precious Metals",
      quantity: 85000,
      price_usd: 185.3,
      market_value_usd: 15750500,
      weight_pct: 37.43,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "United States Oil Fund",
      ticker: "USO",
      isin: "US91232N1081",
      asset_class: "ETF",
      country: "United States",
      sector: "Energy",
      quantity: 420000,
      price_usd: 72.4,
      market_value_usd: 30408000,
      weight_pct: 7.23,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "BHP Group Ltd.",
      ticker: "BHP",
      isin: "AU000000BHP4",
      asset_class: "Equity",
      country: "Australia",
      sector: "Mining",
      quantity: 145000,
      price_usd: 43.2,
      market_value_usd: 6264000,
      weight_pct: 14.89,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "Freeport-McMoRan Inc.",
      ticker: "FCX",
      isin: "US35671D8570",
      asset_class: "Equity",
      country: "United States",
      sector: "Mining",
      quantity: 92000,
      price_usd: 38.7,
      market_value_usd: 3560400,
      weight_pct: 8.46,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "National Iranian Oil Co. Bond",
      ticker: "NIOC26",
      isin: "XS0000000001",
      asset_class: "Bond",
      country: "Iran",
      sector: "Energy",
      quantity: 2000000,
      price_usd: 0.05,
      market_value_usd: 100000,
      weight_pct: 0.24,
      compliance_status: "Restricted",
    },
    {
      fund_id: cr.id,
      security_name: "Glencore PLC",
      ticker: "GLEN",
      isin: "JE00B4T3BW64",
      asset_class: "Equity",
      country: "United Kingdom",
      sector: "Mining",
      quantity: 880000,
      price_usd: 4.95,
      market_value_usd: 4356000,
      weight_pct: 10.35,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "Wheaton Precious Metals",
      ticker: "WPM",
      isin: "CA9628791027",
      asset_class: "Equity",
      country: "Canada",
      sector: "Precious Metals",
      quantity: 68000,
      price_usd: 47.8,
      market_value_usd: 3250400,
      weight_pct: 7.73,
      compliance_status: "Clear",
    },
    {
      fund_id: cr.id,
      security_name: "Vale SA",
      ticker: "VALE",
      isin: "US91912E1055",
      asset_class: "Equity",
      country: "Brazil",
      sector: "Mining",
      quantity: 320000,
      price_usd: 11.2,
      market_value_usd: 3584000,
      weight_pct: 8.52,
      compliance_status: "Clear",
    },
  ]);

  // Fund 4: Multi-Asset Compliance Fund
  await db.insert(positions).values([
    {
      fund_id: macf.id,
      security_name: "Vanguard S&P 500 ETF",
      ticker: "VOO",
      isin: "US9229083632",
      asset_class: "ETF",
      country: "United States",
      sector: "Diversified",
      quantity: 32000,
      price_usd: 458.2,
      market_value_usd: 14662400,
      weight_pct: 26.18,
      compliance_status: "Clear",
    },
    {
      fund_id: macf.id,
      security_name: "iShares Core MSCI Europe ETF",
      ticker: "IEUR",
      isin: "US4642863926",
      asset_class: "ETF",
      country: "United States",
      sector: "Diversified",
      quantity: 145000,
      price_usd: 52.4,
      market_value_usd: 7598000,
      weight_pct: 13.57,
      compliance_status: "Clear",
    },
    {
      fund_id: macf.id,
      security_name: "US Treasury 10Y Note",
      ticker: "TNOTE10",
      isin: "US912810TM89",
      asset_class: "Bond",
      country: "United States",
      sector: "Government",
      quantity: 8000000,
      price_usd: 0.96,
      market_value_usd: 7680000,
      weight_pct: 13.71,
      compliance_status: "Clear",
    },
    {
      fund_id: macf.id,
      security_name: "LVMH Moët Hennessy",
      ticker: "MC",
      isin: "FR0000121014",
      asset_class: "Equity",
      country: "France",
      sector: "Consumer Discretionary",
      quantity: 9800,
      price_usd: 675.0,
      market_value_usd: 6615000,
      weight_pct: 11.81,
      compliance_status: "Clear",
    },
    {
      fund_id: macf.id,
      security_name: "Taiwan Semiconductor Mfg.",
      ticker: "TSM",
      isin: "US8740391003",
      asset_class: "Equity",
      country: "Taiwan",
      sector: "Technology",
      quantity: 42000,
      price_usd: 145.6,
      market_value_usd: 6115200,
      weight_pct: 10.92,
      compliance_status: "Review",
    },
    {
      fund_id: macf.id,
      security_name: "Huawei Technologies Bond 2027",
      ticker: "HUAWEI27",
      isin: "XS1880046175",
      asset_class: "Bond",
      country: "China",
      sector: "Technology",
      quantity: 3500000,
      price_usd: 0.68,
      market_value_usd: 2380000,
      weight_pct: 4.25,
      compliance_status: "Restricted",
    },
    {
      fund_id: macf.id,
      security_name: "Novo Nordisk A/S",
      ticker: "NVO",
      isin: "US6701002056",
      asset_class: "Equity",
      country: "Denmark",
      sector: "Healthcare",
      quantity: 38500,
      price_usd: 118.4,
      market_value_usd: 4558400,
      weight_pct: 8.14,
      compliance_status: "Clear",
    },
    {
      fund_id: macf.id,
      security_name: "iShares Gold ETF",
      ticker: "IAU",
      isin: "US4642851053",
      asset_class: "ETF",
      country: "United States",
      sector: "Precious Metals",
      quantity: 185000,
      price_usd: 38.2,
      market_value_usd: 7067000,
      weight_pct: 12.62,
      compliance_status: "Clear",
    },
  ]);

  console.log("Seed complete. Funds inserted:", insertedFunds.length);
  console.log("Total positions inserted: ~40");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
